// Generated by CoffeeScript 1.3.1
(function() {
  var ws;

  ws = new WebSocket('ws://localhost:8080');

  ws.onmessage = function(message) {
    var avatar, data, player, _i, _len, _ref;
    data = JSON.parse(message.data);
    console.log(data);
    if (data.debrief) {
      _ref = data.debrief;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        player = _ref[_i];
        if (!($('#' + player.ID)[0] != null)) {
          avatar = $('<div class="player", id="' + player.ID + '"></div>');
          avatar.css({
            width: 10,
            height: 10,
            'background-color': 'silver',
            position: 'absolute',
            left: player.x,
            top: player.y
          });
          $('body').append(avatar);
        }
      }
    }
    if (data.disconnect) {
      if ($('#' + data.disconnect)[0] != null) {
        $('#' + data.disconnect).detach();
      }
    }
    if (data.connect) {
      player = data.connect;
      if (!($('#' + player.ID)[0] != null)) {
        avatar = $('<div class="player", id="' + player.ID + '"></div>');
        avatar.css({
          width: 10,
          height: 10,
          'background-color': 'silver',
          position: 'absolute',
          left: player.x,
          top: player.y
        });
        $('body').append(avatar);
      }
    }
    if (data.chat) {
      if ($('#' + data.who)[0] != null) {
        return $('#' + data.who).html(data.chat);
      }
    }
  };

  $('#send').click(function(e) {
    return ws.send(JSON.stringify({
      'chat': $('#chat').val()
    }));
  });

}).call(this);
