// Generated by CoffeeScript 1.3.1
(function() {

  $(window).ready(function() {
    return $.get('./server/js/stderr.log', function(data) {
      var entries, entry, _i, _len;
      console.log("got report..");
      data = data.split("\n");
      entries = [];
      for (_i = 0, _len = data.length; _i < _len; _i++) {
        entry = data[_i];
        entries.push(JSON.parse(entry));
      }
      return console.log(entries);
    });
  });

}).call(this);
