// Generated by CoffeeScript 1.3.1
(function() {
  var fileServer, port, static_, webroot;

  webroot = "../../";

  port = 8075;

  static_ = require("node-static");

  fileServer = new static_.Server(webroot);

  require("http").createServer(function(request, response) {
    return request.addListener("end", function() {
      return fileServer.serve(request, response);
    }).resume();
  }).listen(port);

  console.log("node-static running at http://localhost:%d", port);

}).call(this);
